name: movie_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.3.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_screenutil: ^5.9.3

  # State Management
  flutter_bloc: ^9.1.1

  # Networking
  dio: ^5.9.1
  dio_cookie_manager: ^3.3.0
  pretty_dio_logger: ^1.4.0
  talker_dio_logger: ^5.1.13

  # Local Storage
  shared_preferences: ^2.5.4
  flutter_secure_storage: ^10.0.0

  # DI
  get_it: ^9.2.0

  # Functional Programming
  dartz: ^0.10.1


  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1
  google_sign_in: ^7.2.0
  firebase_core: ^4.9.0

  # Notifications
  flutter_local_notifications: ^19.4.1

  # Utils
  ansicolor: ^2.0.3
  carousel_slider: ^5.1.2
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/

# Splash Screen
flutter_native_splash:
  color: "#121312"
  image: assets/images/splash.png
  fullscreen: true
  android: true
  ios: true
  web: false

  android_12:
    color: "#121312"
    image: assets/images/splash12.png
    icon_background_color: "#121312"

# App Icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#121312"
  adaptive_icon_foreground: "assets/images/logo.png"