// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7K7v-pfJxH5ElnNw9bh2j6d8uN04VPXk',
    appId: '1:507992677598:web:5f66fdb98379f0ac46364f',
    messagingSenderId: '507992677598',
    projectId: 'movies-app-c18-auth',
    authDomain: 'movies-app-c18-auth.firebaseapp.com',
    storageBucket: 'movies-app-c18-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnbmY524uzZoQJmnB4FEqXUPuA2PEv-5g',
    appId: '1:507992677598:android:7acd757beeeaab9c46364f',
    messagingSenderId: '507992677598',
    projectId: 'movies-app-c18-auth',
    storageBucket: 'movies-app-c18-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzevRgOqL3fXyBIKyZpLezQxTqBaTvZbI',
    appId: '1:507992677598:ios:26a64df41c85f84146364f',
    messagingSenderId: '507992677598',
    projectId: 'movies-app-c18-auth',
    storageBucket: 'movies-app-c18-auth.firebasestorage.app',
    iosBundleId: 'com.example.serv5Base',
  );

}